language: go

sudo: required

go:
  - "1.11"

nodejs:
  - "8"

git:
  depth: 3
  quiet: true

env:
  - GO_ENV=test

services:
  - postgresql

addons:
  postgresql: "9.6"

before_script:
  - psql -c 'create database invitation_test;' -U postgres
  - mkdir -p $TRAVIS_BUILD_DIR/public/assets

go_import_path: github.com/invitation

install:
  - go get -v github.com/gobuffalo/buffalo/buffalo
  - go get -v github.com/gobuffalo/suite github.com/gobuffalo/mw-paramlogger github.com/gobuffalo/mw-forcessl github.com/gobuffalo/buffalo-pop github.com/gobuffalo/mw-csrf github.com/gobuffalo/mw-i18n golang.org/x/crypto/bcrypt
  - go get -v $(go list ./... | grep -v /vendor/)
  - yarn
  - GO_ENV=development
  - buffalo build --environment development
  - GO_ENV=test

script: buffalo test -v -coverprofile=c.out ./...

after_script:
  - go tool cover -func=c.out